spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: comanda-service
              uri: "http://api-comandas:8485" # <-- Nomes com hífen e entre aspas!
              predicates:
                - Path=/comanda/**
              filters:
                - StripPrefix=1

            - id: cozinha-service
              uri: "http://api-cozinhas:9090" # <-- Nomes com hífen e entre aspas!
              predicates:
                - Path=/cozinha/**
              filters:
                - StripPrefix=1

            - id: estoque-service
              uri: "http://api-estoque:8082" # <-- Nomes com hífen e entre aspas!
              predicates:
                - Path=/estoque/**
              filters:
                - StripPrefix=1

          # Configurações globais dentro de webflux
          httpclient:
            ssl:
              use-insecure-trust-manager: true

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

server:
  port: 8081