# -----------------------------------------
# Nome da aplicacao e porta
# -----------------------------------------
spring.application.name=comandas-api
server.port=8485

# -----------------------------------------
# Banco de dados
# -----------------------------------------
spring.jpa.show-sql=true
spring.docker.compose.enabled=false

# -----------------------------------------
# Formatacao de datas no JSON
# -----------------------------------------
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo

# -----------------------------------------
# Endereco do servico de cozinha (via gateway)
# -----------------------------------------
# MUDANCA AQUI: URL usando o nome com hifen
cozinha.api.url=http://api-gateway:8081/api/cozinha

# -----------------------------------------
# Logs
# -----------------------------------------
logging.level.org.springframework.web=INFO
logging.level.com.example=DEBUG